
package com.offcn.wode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MobileCodeWSHttpGet", targetNamespace = "http://WebXml.com.cn/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MobileCodeWSHttpGet {

	/**
	 * <br />
	 * <h3>获得国内手机号码归属地省份、地区和手机卡类型信息</h3>
	 * <p>
	 * 输入参数：mobileCode = 字符串（手机号码，最少前7位数字），userID = 字符串（商业用户ID）
	 * 免费用户为空字符串；返回数据：字符串（手机号码：省份 城市 手机卡类型）。
	 * </p>
	 * <br />
	 * 
	 * @param mobileCode
	 * @param userID
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "string", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
	public String getMobileCodeInfo(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mobileCode") String mobileCode,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "userID") String userID);

	/**
	 * <br />
	 * <h3>获得国内手机号码归属地数据库信息</h3>
	 * <p>
	 * 输入参数：无；返回数据：一维字符串数组（省份 城市 记录数量）。
	 * </p>
	 * <br />
	 * 
	 * @return returns com.offcn.wode.ArrayOfString
	 */
	@WebMethod
	@WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
	public ArrayOfString getDatabaseInfo();

}
